# -*- coding: utf-8 -*-
"""
NMCommandHistory — session-wide command history for pyNeuroMatic.

Records each NMMainOp execution as a Python-executable string, serving as
both an audit trail and reusable analysis code.  The primary export target
is a Jupyter notebook (.ipynb); a plain .py script export is also provided.

When ``log_to_nm_history`` is True (the default), each command is also
forwarded to the ``NMHistory`` log (``nm_history.history()``).  This mirrors
Igor NeuroMatic's behaviour where the command appears at the top of the
history window, followed by any output messages generated by that function.

Module-level API
----------------
add_command(cmd)          Log a command string to the global instance.
enable_command_history()  Turn history on  (default: off).
disable_command_history() Turn history off (useful for batch/headless runs).
get_command_history()     Return the global NMCommandHistory instance.
set_command_history(inst) Replace the global instance (testing / NMManager).
"""

from __future__ import annotations

import importlib
import re
from datetime import datetime


# ---------------------------------------------------------------------------
# Modules searched when generating import blocks for notebook/script export.
# Add new tool modules here as they are developed (Stats, Spike, Event, …).
# ---------------------------------------------------------------------------

_IMPORT_SEARCH_MODULES: list[str] = [
    "pyneuromatic.analysis.nm_main_op",
]


def _build_import_block(buffer: list[dict]) -> str:
    """Return a Python import block derived from class names in *buffer*.

    Scans each command string for a leading ``ClassName(`` pattern, then
    locates each class in :data:`_IMPORT_SEARCH_MODULES` and groups them by
    module.  Only classes that are actually used in the history are imported.

    If a class cannot be found in any search module it is silently skipped
    (it will cause a ``NameError`` at replay time, but that is preferable to
    a broken import block).
    """
    # Extract the first token (class name) from each command string.
    class_names: set[str] = set()
    for entry in buffer:
        m = re.match(r"^([A-Z][A-Za-z0-9_]*)\s*\(", entry.get("command", "").strip())
        if m:
            class_names.add(m.group(1))

    if not class_names:
        return "# (no commands recorded)"

    # Map each class name to its source module.
    module_to_classes: dict[str, list[str]] = {}
    for class_name in sorted(class_names):
        for mod_name in _IMPORT_SEARCH_MODULES:
            try:
                mod = importlib.import_module(mod_name)
            except ImportError:
                continue
            if hasattr(mod, class_name):
                module_to_classes.setdefault(mod_name, []).append(class_name)
                break  # stop at the first module that owns this class

    # Format as import statements.
    lines: list[str] = []
    for mod_name in sorted(module_to_classes):
        classes = sorted(module_to_classes[mod_name])
        if len(classes) == 1:
            lines.append("from %s import %s" % (mod_name, classes[0]))
        else:
            lines.append("from %s import (" % mod_name)
            for cls in classes:
                lines.append("    %s," % cls)
            lines.append(")")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# NMCommandHistory class
# ---------------------------------------------------------------------------


class NMCommandHistory:
    """Session-wide store of Python-executable command strings.

    Parameters
    ----------
    enabled:
        When *False* (the default) all :meth:`add` calls are no-ops.  Toggle
        at any time via the :attr:`enabled` property or the module-level
        helpers :func:`enable_command_history` / :func:`disable_command_history`.
        Scripts run without a GUI typically leave this *False*; a GUI calls
        :func:`enable_command_history` (or passes ``command_history=True`` to
        :class:`~pyneuromatic.nm_manager.NMManager`) on startup.
    quiet:
        When *True* commands are stored but not printed to stdout via the
        built-in ``print()`` call.  Note: forwarding to ``NMHistory`` is
        controlled separately by :attr:`log_to_nm_history`.
    log_to_nm_history:
        When *True* (default), each command is also forwarded to the
        ``NMHistory`` log so it appears in the history window before the
        function's own output messages — matching Igor NeuroMatic behaviour.
        Set to *False* to keep command history separate from NMHistory.
    """

    def __init__(
        self,
        enabled: bool = False,
        quiet: bool = False,
        log_to_nm_history: bool = True,
        nm_name: str = "nm",
    ) -> None:
        if not isinstance(enabled, bool):
            raise TypeError("enabled must be a bool, got %r" % type(enabled).__name__)
        if not isinstance(quiet, bool):
            raise TypeError("quiet must be a bool, got %r" % type(quiet).__name__)
        if not isinstance(log_to_nm_history, bool):
            raise TypeError(
                "log_to_nm_history must be a bool, got %r"
                % type(log_to_nm_history).__name__
            )
        if not isinstance(nm_name, str) or not nm_name:
            raise TypeError("nm_name must be a non-empty string")
        self._enabled: bool = enabled
        self._quiet: bool = quiet
        self._log_to_nm_history: bool = log_to_nm_history
        self._nm_name: str = nm_name
        self._buffer: list[dict] = []  # [{"date": ISO_str, "command": str}, ...]

    # ------------------------------------------------------------------
    # Properties

    @property
    def enabled(self) -> bool:
        """Whether command history recording is active."""
        return self._enabled

    @enabled.setter
    def enabled(self, value: bool) -> None:
        if not isinstance(value, bool):
            raise TypeError("enabled must be a bool, got %r" % type(value).__name__)
        self._enabled = value

    @property
    def quiet(self) -> bool:
        """When True, commands are stored but not echoed to stdout."""
        return self._quiet

    @quiet.setter
    def quiet(self, value: bool) -> None:
        if not isinstance(value, bool):
            raise TypeError("quiet must be a bool, got %r" % type(value).__name__)
        self._quiet = value

    @property
    def log_to_nm_history(self) -> bool:
        """When True, forward each command to the NMHistory log."""
        return self._log_to_nm_history

    @log_to_nm_history.setter
    def log_to_nm_history(self, value: bool) -> None:
        if not isinstance(value, bool):
            raise TypeError(
                "log_to_nm_history must be a bool, got %r" % type(value).__name__
            )
        self._log_to_nm_history = value

    @property
    def buffer(self) -> list[dict]:
        """Return a shallow copy of the history buffer.

        Each entry is a dict with keys ``"date"`` (ISO-8601 string) and
        ``"command"`` (the recorded command string).
        """
        return list(self._buffer)

    @property
    def nm_name(self) -> str:
        """Variable name used for the NMManager instance (default ``"nm"``).

        Used by :meth:`add_nm` to prefix commands with ``nm_name + suffix``.
        Change this if your script uses a different variable name, e.g.
        ``manager`` or ``my_nm``.
        """
        return self._nm_name

    @nm_name.setter
    def nm_name(self, value: str) -> None:
        if not isinstance(value, str) or not value:
            raise TypeError("nm_name must be a non-empty string")
        self._nm_name = value

    # ------------------------------------------------------------------
    # Core

    def add(self, command_str: str) -> None:
        """Append *command_str* to the buffer with a timestamp.

        Does nothing when :attr:`enabled` is *False*.

        If :attr:`log_to_nm_history` is *True*, the command is also forwarded
        to ``nm_history.history()`` so it appears in the NMHistory window
        before any output messages generated by the op — mirroring Igor
        NeuroMatic behaviour.  ``path="NONE"`` is passed so no function-path
        prefix is prepended to the command string.

        If :attr:`quiet` is *False* **and** :attr:`log_to_nm_history` is
        *False*, the command is printed directly to stdout.  When
        ``log_to_nm_history`` is True the NMHistory console handler controls
        display, so the direct ``print()`` is skipped to avoid duplication.
        """
        if not self._enabled:
            return
        if not isinstance(command_str, str):
            raise TypeError(
                "command_str must be a str, got %r" % type(command_str).__name__
            )
        entry = {"date": datetime.now().isoformat(), "command": command_str}
        self._buffer.append(entry)
        if self._log_to_nm_history:
            import pyneuromatic.core.nm_history as _nmh
            _nmh.history(command_str, path="NONE")
        elif not self._quiet:
            print(command_str)

    def add_nm(self, suffix: str) -> None:
        """Log a command prefixed with :attr:`nm_name` and a dot.

        Equivalent to ``self.add(self.nm_name + "." + suffix)``.  Use this
        for all NMManager attribute/method calls so the variable name is kept
        in one place::

            history.add_nm("tool_add('main')")     # → "nm.tool_add('main')"
            history.add_nm("tool_select = 'main'") # → "nm.tool_select = 'main'"
        """
        self.add(self._nm_name + "." + suffix)

    def clear(self) -> None:
        """Remove all entries from the buffer."""
        self._buffer.clear()

    def __len__(self) -> int:
        return len(self._buffer)

    # ------------------------------------------------------------------
    # Display

    def print_all(self, last_n: int = 0) -> None:
        """Print buffer contents to stdout.

        Parameters
        ----------
        last_n:
            Number of most-recent entries to print.  ``0`` (default) prints
            all entries.
        """
        entries = self._buffer if last_n == 0 else self._buffer[-last_n:]
        for entry in entries:
            print("# %s" % entry["date"])
            print(entry["command"])
            print()

    # ------------------------------------------------------------------
    # Export

    def to_notebook(self, filepath: str, title: str = "NMCommandHistory") -> None:
        """Export the buffer as a Jupyter notebook (.ipynb).

        Notebook structure
        ~~~~~~~~~~~~~~~~~~
        * Cell 0 (markdown) — title heading + generation date-time
        * Cell 1 (code)     — import block
        * Cells 2+          — one code cell per command; ISO timestamp as
                              a leading comment inside the cell

        Parameters
        ----------
        filepath:
            Destination path (should end in ``.ipynb``).
        title:
            Notebook title shown in the first markdown cell.
        """
        try:
            import nbformat
        except ImportError as exc:
            raise ImportError(
                "nbformat is required for notebook export.  "
                "Install it with: pip install nbformat"
            ) from exc

        nb = nbformat.v4.new_notebook()

        # --- Cell 0: markdown title ---
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        md_source = "# %s\n\nGenerated: %s" % (title, now_str)
        nb.cells.append(nbformat.v4.new_markdown_cell(md_source))

        # --- Cell 1: imports (derived from commands actually in the buffer) ---
        nb.cells.append(nbformat.v4.new_code_cell(_build_import_block(self._buffer)))

        # --- One cell per command ---
        for entry in self._buffer:
            cell_source = "# %s\n%s" % (entry["date"], entry["command"])
            nb.cells.append(nbformat.v4.new_code_cell(cell_source))

        with open(filepath, "w", encoding="utf-8") as fh:
            nbformat.write(nb, fh)

    def to_script(self, filepath: str) -> None:
        """Export the buffer as a plain Python script (.py).

        Each command is written as a top-level statement preceded by a
        ``# date`` comment.

        Parameters
        ----------
        filepath:
            Destination path (should end in ``.py``).
        """
        lines = [
            "# NMCommandHistory export",
            "# Generated: %s" % datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "",
            _build_import_block(self._buffer),
            "",
        ]
        for entry in self._buffer:
            lines.append("# %s" % entry["date"])
            lines.append(entry["command"])
            lines.append("")

        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))


# ---------------------------------------------------------------------------
# Module-level global instance and convenience API
# ---------------------------------------------------------------------------

_nm_command_history: NMCommandHistory = NMCommandHistory(quiet=True, log_to_nm_history=True)


def add_command(command_str: str) -> None:
    """Log *command_str* to the global :class:`NMCommandHistory` instance."""
    _nm_command_history.add(command_str)


def add_nm_command(suffix: str) -> None:
    """Log a command prefixed with the global instance's :attr:`~NMCommandHistory.nm_name`."""
    _nm_command_history.add_nm(suffix)


def enable_command_history() -> None:
    """Enable recording on the global instance."""
    _nm_command_history.enabled = True


def disable_command_history() -> None:
    """Disable recording on the global instance (e.g. for batch runs)."""
    _nm_command_history.enabled = False


def get_command_history() -> NMCommandHistory:
    """Return the global :class:`NMCommandHistory` instance."""
    return _nm_command_history


def set_command_history(instance: NMCommandHistory) -> None:
    """Replace the global instance.

    Intended for use by :class:`~pyneuromatic.nm_manager.NMManager` or tests
    that need an isolated history object.
    """
    global _nm_command_history
    if not isinstance(instance, NMCommandHistory):
        raise TypeError(
            "instance must be an NMCommandHistory, got %r"
            % type(instance).__name__
        )
    _nm_command_history = instance
